### ISSUE TITLE
[bug] Resynchronize library with Sharenite cancels itself 

### ISSUE THREAD

**Issue by BloodShed-Oni** [sharenite/playnite-sharenite#22]
When using the 'Resynchronize library with Sharenite' the process will run for a minute and then end with this error message.
![image](https://github.com/sharenite/playnite-sharenite/assets/10365453/bcf9c2b8-d6d2-4adc-86e7-4952bf68693a)

Here's the extension log
```
08-11 16:00:22.287|ERROR|Sharenite#Sharenite:Sharenite synchronization failed.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharenite.Services.ShareniteAccountClient.<SynchroniseGames>d__20.MoveNext() in C:\Users\dawid\Projects\Playnite\playnite-sharenite\Services\ShareniteAccountClient.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Sharenite.Sharenite.<>c__DisplayClass15_0.<SynchroniseGames>b__0(GlobalProgressActionArgs args) in C:\Users\dawid\Projects\Playnite\playnite-sharenite\Sharenite.cs:line 76
   at Playnite.ViewModels.ProgressViewViewModel.<>c__DisplayClass22_0.<ActivateProgress>b__0() in C:\projects\playnite\source\Playnite\ViewModels\ProgressViewViewModel.cs:line 91
```

**Comment by XenorPLxx** [comment]
I knew this day would come eventually :).

I'd probably have to reimplement code to do partial sends instead of trying to send a huge library at once.

As a way around for now, you can use filters for partial sync, e.g. select only one category/tag/platform, ctrl+a, right click on any game and choose 'Synchronize... Sharenite' option, repeat for all filters.

**Comment by XenorPLxx** [comment]
Referencing https://github.com/JosefNemec/Playnite/commit/c8b8c7e47d3113b344dd39b57dfc30e82a16e21e as potential additional improvement to the process

**Comment by XenorPLxx** [comment]
Triage update (2026-03-02):
- Status: `not covered`
- Priority: `P0`
- Makes sense: `yes`
- Notes: High-severity reliability bug in sync flow (canceling itself). Should be handled first.
